(** Generate Python modules *)

val internal_module : generated_module:string -> string
(** Conventional name of the internal module generated by [pyml], to be imported
    within [<generated_module>.py] (see [GENERATED_BY_PYML] in [stub.py]) *)

val create_module : name:string -> Repr.value list -> unit
(** Generate and register a Python module given a list of value declarations. *)
