(** Generate Python modules *)

val internal_module : generated:string -> string
(** Name of the internal module generated by {!create_module}. *)

val create_module : generated:string -> Repr.value list -> unit
(** Generate and register a Python module with name [internal_module ~generated]
    given a list of value declarations. *)
