# Autogenerated by python_library_in_ocaml

from ctypes import RTLD_LOCAL, PyDLL, c_char_p

from importlib.resources import files, as_file

DLL_NAME = "ocaml_module.so"

dll_resource = files("mylib.bin").joinpath(DLL_NAME)
with as_file(dll_resource) as dll_file:
    dll = PyDLL(str(dll_file), RTLD_LOCAL)

argv_t = c_char_p * 3
argv = argv_t(DLL_NAME.encode("utf-8"), b"register", None)
dll.caml_startup(argv)

import _ocaml_module_internals  # type: ignore


Expr = ...
Result = ...
CustommerData = ...


def eval(valuation, expr):
    return _ocaml_module_internals.eval(valuation, expr)


def fact(n):
    return _ocaml_module_internals.fact(n)


def custommer_data(name):
    return _ocaml_module_internals.custommer_data(name)
